"""
Django settings for myWebRoot project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

import environ

# Inicializar environ
env = environ.Env(
    # Valores por defecto
    DEBUG=(bool, True),
    CELERY_BROKER_URL=(str, "memory://localhost/"),
    EMAIL_HOST=(str, "localhost"),
    EMAIL_PORT=(int, 587),
    EMAIL_USE_TLS=(bool, True),
    EMAIL_HOST_USER=(str, ""),
    EMAIL_HOST_PASSWORD=(str, ""),
    DEFAULT_FROM_EMAIL=(str, "noreply@rootapp.com"),
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Tomar variables de entorno del archivo .env
environ.Env.read_env(Path(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY", default="django-insecure-l0_w*4m-dr%0!h2o*gvoq3ht13e^5wj+smm1dx%67fm69nk=c4")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])

# Configuración del modelo de usuario personalizado
AUTH_USER_MODEL = "usuarios.Usuario"

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
    "carrito",
    "facturas",
    "pagos",
    "productos",
    "scanner",
    "usuarios",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "myWebRoot.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [Path(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "myWebRoot.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": env.db("DATABASE_URL", default=f'sqlite:///{BASE_DIR / "db.sqlite3"}'),
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = env("LANGUAGE_CODE", default="es-co")  # Cambiado a español Colombia

TIME_ZONE = env("TIME_ZONE", default="America/Bogota")  # Cambiado a zona horaria de Colombia

USE_I18N = True

USE_TZ = True

STATIC_URL = env("STATIC_URL", default="/static/")

# Asegúrate de crear esta carpeta si no existe
STATIC_ROOT = Path(BASE_DIR, "staticfiles")

# Corregida la ruta de STATICFILES_DIRS
STATICFILES_DIRS = [
    Path(BASE_DIR, "static"),  # Cambié mywWebRoot por static
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# URLs de redirección para login
LOGIN_URL = env("LOGIN_URL", default="/usuarios/login/")
LOGIN_REDIRECT_URL = env("LOGIN_REDIRECT_URL", default="/scanner/scanner/")
LOGOUT_REDIRECT_URL = env("LOGOUT_REDIRECT_URL", default="/")

# Configuración para archivos de medios
MEDIA_URL = env("MEDIA_URL", default="/media/")
MEDIA_ROOT = Path(BASE_DIR, "media")

# Cache settings
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",
    },
}

# Configuración de Email
EMAIL_BACKEND = env("EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = env("EMAIL_HOST")
EMAIL_PORT = env("EMAIL_PORT")
EMAIL_USE_TLS = env("EMAIL_USE_TLS")
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL")

# Configuración básica de Celery
CELERY_BROKER_URL = env("CELERY_BROKER_URL")

# Configuración de sesión
SESSION_COOKIE_AGE = 3600  # 1 hora por defecto
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Si no marcan "recordarme"
SESSION_SAVE_EVERY_REQUEST = True
