# Exclude a variety of commonly ignored directories.
exclude = [
   ".bzr",
   ".direnv",
   ".eggs",
   ".git",
   ".git-rewrite",
   ".hg",
   ".ipynb_checkpoints",
   ".mypy_cache",
   ".nox",
   ".pants.d",
   ".pyenv",
   ".pytest_cache",
   ".pytype",
   ".ruff_cache",
   ".svn",
   ".tox",
   ".venv",
   ".vscode",
   "__pypackages__",
   "_build",
   "buck-out",
   "build",
   "dist",
   "node_modules",
   "site-packages",
   "virtual", #Es tu entorno virtual tiene bibliotecas que no puedo controlar y no debo modificar.
   "migrations", #Las migraciones son generadas automaticamente por Django. Modificarlas manualmente puede causar problemas graves en la base de datos.
   ".gitignore", #Es un archivo de configuración de Git, no codigo Python. Ruff no lo analiza.
   "myWebRoot/manage.py", #Es parte de la estructura estandar de Django. Su formato esta definido por el framework y no debe modificarse ni ser analizado.
   "PLR0911", 
   "TRY300", #estas dos ultimas reglas no encuetro como silenciarlas y a pesar que las ignoro siguen aparaciendo.
]


# Same as Black.
line-length = 250
indent-width = 4

target-version = "py313"

[lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = ["ALL"]
ignore = ["D203", "D212","N999"]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
# skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
# docstring-code-format = false

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"