# Generated by Django 5.1.6 on 2025-04-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodopago',
            name='tipo',
            field=models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('paypal', 'PayPal'), ('mercadopago', 'MercadoPago'), ('movil', 'Pago Móvil')], max_length=20),
        ),
    ]
