# Generated by Django 5.1.6 on 2025-04-03 20:44

import django.db.models.deletion
from django.db import migrations, models

import productos.models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
            },
        ),
        migrations.AlterModelOptions(
            name="producto",
            options={"verbose_name": "Producto", "verbose_name_plural": "Productos"},
        ),
        migrations.RemoveIndex(
            model_name="producto",
            name="productos_p_nombre_456643_idx",
        ),
        migrations.RemoveIndex(
            model_name="producto",
            name="productos_p_precio_d043df_idx",
        ),
        migrations.AddField(
            model_name="producto",
            name="fecha_actualizacion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="codigo",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to=productos.models.producto_imagen_path),
        ),
        migrations.AlterField(
            model_name="producto",
            name="nombre",
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name="producto",
            name="categoria",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="productos", to="productos.categoria"),
        ),
    ]
